Move workflow validation to validate_secrets 1/2

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -1,6 +1,12 @@
 name: 1. Validate Secrets
-run-name: Validate Secrets
-on: [workflow_call, workflow_dispatch]
+run-name: Validate Secrets (${{ github.ref_name }})
+on: 
+  workflow_call:
+    outputs: 
+      WORKFLOW_PERMISSION: 
+        description: "GH_PAT holds workflow permission or is fine-grained PAT."
+        value: ${{ jobs.validate-workflow-permission.outputs.WORKFLOW_PERMISSION }}
+  workflow_dispatch:
 
 jobs:
   validate-access-token:
@@ -15,17 +21,42 @@ jobs:
           # Validate Fastlane Access Token (GH_PAT)
           if [ -z "$GH_PAT" ]; then
             failed=true
-            echo "::error::GH_PAT secret is unset or empty. Set it and try again."
+            echo "::error::The GH_PAT secret is unset or empty. Set it and try again."
           elif [ "$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/LoopWorkspace | jq --raw-output '.permissions.push')" != "true" ]; then
             failed=true
-            echo "::error::GH_PAT secret is set but invalid or lacking 'repo' permission scope. Verify that it is created/set correctly and try again."
+            echo "::error::The GH_PAT secret is set but invalid or lacking at least 'repo' permission scope ('repo, workflow' is okay too).\
+            Verify that token permissions are set correctly (or update them) at https://github.com/settings/tokens and try again."
           fi
           
           # Exit unsuccessfully if secret validation failed.
           if [ $failed ]; then
             exit 2
           fi
-          
+
+  validate-workflow-permission:
+    needs: validate-access-token
+    runs-on: macos-13
+    name: Workflow Permission
+    outputs:
+      WORKFLOW_PERMISSION: ${{ steps.workflow-permission.outputs.has_permission }}
+      
+    steps:
+    - name: Validate Workflow Permission
+      id: workflow-permission
+      env: 
+        TOKEN_TO_CHECK: ${{ secrets.GH_PAT }}
+      run: |
+        PERMISSIONS=$(curl -sS -f -I -H "Authorization: token ${{ env.TOKEN_TO_CHECK }}" https://api.github.com | grep ^x-oauth-scopes: | cut -d' ' -f2-);
+        
+        if [[ $PERMISSIONS =~ "workflow" || $PERMISSIONS == "" ]]; then
+          echo "GH_PAT holds workflow permissions or is fine-grained PAT."
+          echo "has_permission=true" >> $GITHUB_OUTPUT # Set WORKFLOW_PERMISSION to false.
+        else 
+          echo "GH_PAT lacks workflow permissions."
+          echo "Automated build features will be skipped!"
+          echo "has_permission=false" >> $GITHUB_OUTPUT # Set WORKFLOW_PERMISSION to false.
+        fi
+  
   validate-match-secrets:
     name: Match-Secrets
     needs: validate-access-token
@@ -40,22 +71,22 @@ jobs:
             echo "A 'Match-Secrets' repository could not be found. Attempting to create one...";
             
             if gh repo create Match-Secrets --private >/dev/null && [ "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility == "PRIVATE"')" == "true" ]; then
-              echo "Created a 'Match-Secrets' private repository."
+              echo "Created a private 'Match-Secrets' repository."
             else
               failed=true
-              echo "::error::A private 'Match-Secrets' repository could not be created. Create a private `Match-Secrets` repository manually or try again.\
-              If a private 'Match-Secrets' repository already exists, ensure that the GH_PAT has appropriate permissions to access it."
+              echo "::error::Cannot access or create a private 'Match-Secrets' repository. The GH_PAT secret is lacking at least the 'repo' permission scope required to access or create the repository.\
+              Verify that token permissions are set correctly (or update them) at https://github.com/settings/tokens and try again."
             fi
           elif [ "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility == "PUBLIC"')" == "true" ]; then
             failed=true
             echo "::error::A 'Match-Secrets' repository was found, but it is is public. Delete it and try again (a private repository will be created for you)."
           fi
-
+          
           # Exit unsuccessfully if secret validation failed.
           if [ $failed ]; then
             exit 2
           fi
-          
+  
   validate-fastlane-secrets:
     name: Fastlane
     needs: validate-match-secrets
@@ -71,7 +102,7 @@ jobs:
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v3
-      
+        
       - name: Validate Fastlane Secrets
         run: |
           # Validate Fastlane Secrets
@@ -79,13 +110,13 @@ jobs:
           # Validate TEAMID
           if [ -z "$TEAMID" ]; then
             failed=true
-            echo "::error::TEAMID secret is unset or empty. Set it and try again."
+            echo "::error::The TEAMID secret is unset or empty. Set it and try again."
           elif [ ${#TEAMID} -ne 10 ]; then
             failed=true
-            echo "::error::TEAMID secret is set but has wrong length. Verify that it is set correctly and try again."
+            echo "::error::The TEAMID secret is set but has wrong length. Verify that it is set correctly and try again."
           elif ! [[ $TEAMID =~ ^[A-Z0-9]+$ ]]; then
             failed=true
-            echo "::error::TEAMID is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
+            echo "::error::The TEAMID secret is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
           fi
           
           # Validate MATCH_PASSWORD
@@ -93,6 +124,9 @@ jobs:
             failed=true
             echo "::error::The MATCH_PASSWORD secret is unset or empty. Set it and try again."
           fi
+          
+          # Ensure that fastlane exit codes are handled when output is piped.
+          set -o pipefail
           
           # Validate FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY
           FASTLANE_KEY_ID_PATTERN='^[A-Z0-9]+$'
@@ -105,21 +139,22 @@ jobs:
             [ -z "$FASTLANE_KEY"       ] && echo "::error::The FASTLANE_KEY secret is unset or empty. Set it and try again."
           elif [ ${#FASTLANE_KEY_ID} -ne 10 ]; then
             failed=true
-            echo "::error::FASTLANE_KEY_ID secret is set but has wrong length. Verify that it is set correctly and try again."
+            echo "::error::The FASTLANE_KEY_ID secret is set but has wrong length. Verify that you copied it correctly from the 'Keys' tab at https://appstoreconnect.apple.com/access/api and try again."
           elif ! [[ $FASTLANE_KEY_ID =~ $FASTLANE_KEY_ID_PATTERN ]]; then
             failed=true
-            echo "::error::FASTLANE_KEY_ID is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
+            echo "::error::The FASTLANE_KEY_ID secret is set but invalid. Verify that you copied it correctly from the 'Keys' tab at https://appstoreconnect.apple.com/access/api and try again."
           elif ! [[ $FASTLANE_ISSUER_ID =~ $FASTLANE_ISSUER_ID_PATTERN ]]; then
             failed=true
-            echo "::error::FASTLANE_ISSUER_ID is set but invalid. Verify that it is set correctly (adhering to UUID format) and try again."
+            echo "::error::The FASTLANE_ISSUER_ID secret is set but invalid. Verify that you copied it correctly from the 'Keys' tab at https://appstoreconnect.apple.com/access/api and try again."
           elif ! echo "$FASTLANE_KEY" | openssl pkcs8 -nocrypt >/dev/null; then
             failed=true
-            echo "::error::The FASTLANE_KEY secret is set but invalid. Verify that it is set correctly and try again."
+            echo "::error::The FASTLANE_KEY secret is set but invalid. Verify that you copied it correctly from the API Key file (*.p8) you downloaded and try again."
           elif ! fastlane validate_secrets 2>&1 | tee fastlane.log; then
-            failed=true
             if grep -q "bad decrypt" fastlane.log; then
+              failed=true
               echo "::error::Unable to decrypt the Match-Secrets repository using the MATCH_PASSWORD secret. Verify that it is set correctly and try again."
-            else
+            elif ! grep -q "No code signing identity found" fastlane.log; then
+              failed=true
               echo "::error::Unable to create a valid authorization token for the App Store Connect API.\
               Verify that the FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY secrets are set correctly and try again."
             fi
