Update validate_secrets.yml

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -1,24 +1,54 @@
 name: 1. Validate Secrets
 run-name: Validate Secrets
 on: [workflow_call, workflow_dispatch]
-  
+
 jobs:
-  validate-token:
-    name: Validate GH_PAT
+  validate-access-token:
+    name: Access
     runs-on: macos-13
+    env:
+      GH_PAT: ${{ secrets.GH_PAT }}
+      GH_TOKEN: ${{ secrets.GH_PAT }}
     steps:
-      - name: Validate GH_PAT
-        env:
-          GH_PAT: ${{ secrets.GH_PAT }}
-          GH_TOKEN: ${{ secrets.GH_PAT }}
+      - name: Validate Access Token
         run: |
-          # Validate GH_PAT
+          # Validate Fastlane Access Token (GH_PAT)
           if [ -z "$GH_PAT" ]; then
             failed=true
             echo "::error::GH_PAT secret is unset or empty. Set it and try again."
           elif [ "$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/LoopWorkspace | jq --raw-output '.permissions.push')" != "true" ]; then
             failed=true
-            echo "::error::GH_PAT secret is set but invalid or lacking REPO permission. Verify that it is set correctly and try again."
+            echo "::error::GH_PAT secret is set but invalid or lacking 'repo' permission scope. Verify that it is created/set correctly and try again."
+          fi
+          
+          # Exit unsuccessfully if secret validation failed.
+          if [ $failed ]; then
+            exit 2
+          fi
+          
+  validate-match-secrets:
+    name: Match-Secrets
+    needs: validate-access-token
+    runs-on: macos-13
+    env:
+      GH_TOKEN: ${{ secrets.GH_PAT }}
+    steps:
+      - name: Validate Match-Secrets
+        run: |
+          # Validate Match-Secrets
+          if [ "$(gh repo list --json name | jq --raw-output 'any(.name=="Match-Secrets")')" != "true" ]; then
+            echo "A 'Match-Secrets' repository could not be found. Attempting to create one...";
+            
+            if [ gh repo create Match-Secrets --private && "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility == "PRIVATE"')" == "true" ]; then
+              echo "Created a 'Match-Secrets' private repository."
+            else
+              failed=true
+              echo "::error::A private 'Match-Secrets' repository could not be created. Create a private `Match-Secrets` repository manually or try again.\
+              If a private 'Match-Secrets' repository already exists, ensure that the GH_PAT has appropriate permissions to access it."
+            fi
+          elif [ "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility == "PUBLIC"')" == "true" ]; then
+            failed=true
+            echo "::error::A 'Match-Secrets' repository was found, but it is is public. Delete it and try again (a private repository will be created for you)."
           fi
 
           # Exit unsuccessfully if secret validation failed.
@@ -26,48 +56,25 @@ jobs:
             exit 2
           fi
           
-  infrastructure:
-    name: Prepare infrastructure
-    needs: validate-token
+  validate-fastlane-secrets:
+    name: Fastlane
+    needs: validate-match-secrets
     runs-on: macos-13
     env:
+      GH_PAT: ${{ secrets.GH_PAT }}
       GH_TOKEN: ${{ secrets.GH_PAT }}
+      FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
+      FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
+      FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
+      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+      TEAMID: ${{ secrets.TEAMID }}
     steps:
-      # Checks-out the repo
-      - name: Check Match-Secrets existence and create
-        env: 
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          echo "Validating existence of Match-Secrets repository... "
-          if [ "$(gh repo list --json name | jq --raw-output 'any(.name=="matchtest")')" != "true" ]; then
-            echo "No Match-Secrets repository found... ";
-            echo "Creating private repository... ";
-            gh repo create matchtest --private
-            
-            if [ "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility == "PRIVATE"')" == "true" ]; then
-              echo "Successfully created Match-Secrets repository"
-            else
-              # Exit unsuccessfully if creation failed.
-              echo "::error::Private `Match-Secrets` repository could not be created! Please try again."
-              exit 2
-            fi
-          else
-            echo "Match-Secrets repository already exists! Proceeding with validation of repository secrets... ";
-          fi
-
-  validate:
-    name: Validate other secrets
-    needs: infrastructure
-    runs-on: macos-13
-    steps:
-      # Checks-out the repo
       - name: Checkout Repo
         uses: actions/checkout@v3
-       
-      - name: Validate Secrets
+      
+      - name: Validate Fastlane Secrets
         run: |
-          # Validate Secrets
-          echo Validating Repository Secrets...
+          # Validate Fastlane Secrets
           
           # Validate TEAMID
           if [ -z "$TEAMID" ]; then
@@ -81,9 +88,13 @@ jobs:
             echo "::error::TEAMID is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
           fi
           
+          # Validate MATCH_PASSWORD
+          if [ -z "$MATCH_PASSWORD" ]; then
+            failed=true
+            echo "::error::The MATCH_PASSWORD secret is unset or empty. Set it and try again."
+          fi
+          
           # Validate FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY
-          FASTLANE_KEY_ID_PATTERN='^[A-Z0-9]+$'
-          FASTLANE_ISSUER_ID_PATTERN='^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$'
           if [ -z "$FASTLANE_ISSUER_ID" ] || [ -z "$FASTLANE_KEY_ID" ] || [ -z "$FASTLANE_KEY" ]; then
             failed=true
             [ -z "$FASTLANE_ISSUER_ID" ] && echo "::error::The FASTLANE_ISSUER_ID secret is unset or empty. Set it and try again."
@@ -101,37 +112,17 @@ jobs:
           elif ! echo "$FASTLANE_KEY" | openssl pkcs8 -nocrypt >/dev/null; then
             failed=true
             echo "::error::The FASTLANE_KEY secret is set but invalid. Verify that it is set correctly and try again."
-          elif ! fastlane validate_secrets; then
+          elif ! fastlane validate_secrets 2>&1 | tee fastlane.log; then
             failed=true
-            echo "::error::Unable to create a valid authorization token for the App Store Connect API.\
-            Verify that the FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY secrets are set correctly and try again."
-          fi
-          
-          # Validate MATCH_PASSWORD
-          match_secrets_status=$((gh api --method GET -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" /repos/dnzxy/Test-Repo/commits --silent -i || true) | head -n 1 | cut -d$' ' -f2)
-            # Note: adding "|| true“ here avoid action to exit on commit query resulting in HTTP status 409
-            # By default this would result in a non-zero exit code.
-          
-          if [ -z "$MATCH_PASSWORD" ]; then
-            failed=true
-            echo "::error::The MATCH_PASSWORD secret is unset or empty. Set it and try again."
-          elif [ "$match_secrets_status"=="200" && "$match_secrets_status"!="409" ]; then
-            echo Checking MATCH_PASSWORD passphrase validity...
-
-            # TODO: perform fastlane match readonly here
-            
+            if grep -q "bad decrypt" fastlane.log; then
+              echo "::error::Unable to decrypt the Match-Secrets repository using the MATCH_PASSWORD secret. Verify that it is set correctly and try again."
+            else
+              echo "::error::Unable to create a valid authorization token for the App Store Connect API.\
+              Verify that the FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY secrets are set correctly and try again."
+            fi
           fi
           
           # Exit unsuccessfully if secret validation failed.
           if [ $failed ]; then
             exit 2
           fi
-        shell: bash
-        env:
-          TEAMID: ${{ secrets.TEAMID }}
-          GH_PAT: ${{ secrets.GH_PAT }}
-          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
-          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
-          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
-          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
-          GH_TOKEN: ${{ secrets.GH_PAT }} # necessary to set this, so that gh CLI commands in validate step use the Looper's GH_PAT
