Re-arrange token checks

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -3,8 +3,33 @@ run-name: Validate Secrets
 on: [workflow_call, workflow_dispatch]
   
 jobs:
-  infrastructure:
+  validate-token:
     runs-on: macos-13
+    steps:
+      - name: Validate GH_PAT
+        env:
+          GH_PAT: ${{ secrets.GH_PAT }}
+          GH_TOKEN: ${{ secrets.GH_PAT }}
+        run: |
+          # Validate GH_PAT
+          if [ -z "$GH_PAT" ]; then
+            failed=true
+            echo "::error::GH_PAT secret is unset or empty. Set it and try again."
+          elif [ "$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/Match-Secrets | jq --raw-output '.permissions.push')" != "true" ]; then
+            failed=true
+            echo "::error::GH_PAT secret is set but invalid or lacking appropriate privileges on the ${{ github.repository_owner }}/Match-Secrets repository. Verify that it is set correctly and try again."
+          fi
+
+          # Exit unsuccessfully if secret validation failed.
+          if [ $failed ]; then
+            exit 2
+          fi
+          
+  infrastructure:
+    needs: validate-token
+    runs-on: macos-13
+    env:
+      GH_TOKEN: ${{ secrets.GH_PAT }}
     steps:
       # Checks-out the repo
       - name: Check Match-Secrets existence and create
@@ -52,24 +77,6 @@ jobs:
           elif ! [[ $TEAMID =~ ^[A-Z0-9]+$ ]]; then
             failed=true
             echo "::error::Match-Secrets repository could not be created! is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
-          fi
-          
-          # Validate GH_PAT
-          if [ -z "$GH_PAT" ]; then
-            failed=true
-            echo "::error::GH_PAT secret is unset or empty. Set it and try again."
-          elif [ "$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/Match-Secrets | jq --raw-output '.permissions.push')" != "true" ]; then
-            failed=true
-            echo "::error::GH_PAT secret is set but invalid or lacking appropriate privileges on the ${{ github.repository_owner }}/Match-Secrets repository. Verify that it is set correctly and try again."
-          
-          # Legacy browser builder validations (in case they modify their setup)!
-          
-          elif [ "$(gh repo list --json name | jq --raw-output 'any(.name=="Match-Secrets")')" != "true" ]; then
-            failed=true
-            echo "::error::GH_PAT secret is set but Match-Secrets repository is missing or configured incorrectly. Verify that the repository was created and that its name is spelled correctly (uppercase 'M' for 'Match', uppercase 'S' and plural for 'Secrets', dash character '-' between the words as separator)."
-          elif [ "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility')" != "PRIVATE" ]; then
-            failed=true
-            echo "::error::Match-Secrets repository visibility is set to PUBLIC. Set it to PRIVATE and try again."
           fi
           
           # Validate FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY
