Fix non-zero exit code for gh api call

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -108,7 +108,10 @@ jobs:
           fi
           
           # Validate MATCH_PASSWORD
-          match_secrets_status=$(gh api --method GET -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" /repos/dnzxy/Test-Repo/commits --silent -i | head -n 1 | cut -d$' ' -f2)
+          match_secrets_status=$((gh api --method GET -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" /repos/dnzxy/Test-Repo/commits --silent -i || true) | head -n 1 | cut -d$' ' -f2)
+            # Note: adding "|| true“ here avoid action to exit on commit query resulting in HTTP status 409
+            # By default this would result in a non-zero exit code.
+          
           if [ -z "$MATCH_PASSWORD" ]; then
             failed=true
             echo "::error::The MATCH_PASSWORD secret is unset or empty. Set it and try again."
