Check match-secrets and create if non-existent

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -3,13 +3,39 @@ run-name: Validate Secrets
 on: [workflow_call, workflow_dispatch]
   
 jobs:
+  infrastructure:
+    runs-on: macos-13
+    steps:
+      # Checks-out the repo
+      - name: Check Match-Secrets existence and create
+        env: 
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo "Validating existence of Match-Secrets repository... "
+          if [ "$(gh repo list --json name | jq --raw-output 'any(.name=="Match-Secrets")')" != "true" ]; then
+            echo "No Match-Secrets repository found... ";
+            echo "Creating private repository... ";
+            gh repo create Match-Secrets --private
+            
+            if [ "$(gh repo list --json name,visibility | jq --raw-output 'any(.name=="Match-Secrets")')" == "true" ]; then
+              echo "Successfully created Match-Secrets repository"
+            else
+              # Exit unsuccessfully if creation failed.
+              echo "::error::Private `Match-Secrets` repository could not be created! Please try again."
+              exit 2
+            fi
+          else
+            echo "Match-Secrets repository already exists! Proceeding with validation of repository secrets... ";
+          fi
+
   validate:
-    runs-on: macos-12
+    runs-on: macos-13
+    needs: infrastructure
     steps:
       # Checks-out the repo
       - name: Checkout Repo
         uses: actions/checkout@v3
-      
+       
       # Validates the repo secrets
       - name: Validate Secrets
         run: |
@@ -25,7 +51,7 @@ jobs:
             echo "::error::TEAMID secret is set but has wrong length. Verify that it is set correctly and try again."
           elif ! [[ $TEAMID =~ ^[A-Z0-9]+$ ]]; then
             failed=true
-            echo "::error::TEAMID is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
+            echo "::error::Match-Secrets repository could not be created! is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
           fi
           
           # Validate GH_PAT
@@ -35,9 +61,15 @@ jobs:
           elif [ "$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/Match-Secrets | jq --raw-output '.permissions.push')" != "true" ]; then
             failed=true
             echo "::error::GH_PAT secret is set but invalid or lacking appropriate privileges on the ${{ github.repository_owner }}/Match-Secrets repository. Verify that it is set correctly and try again."
+          
+          # Legacy browser builder validations (in case they modify their setup)!
+          
           elif [ "$(gh repo list --json name | jq --raw-output 'any(.name=="Match-Secrets")')" != "true" ]; then
             failed=true
             echo "::error::GH_PAT secret is set but Match-Secrets repository is missing or configured incorrectly. Verify that the repository was created and that its name is spelled correctly (uppercase 'M' for 'Match', uppercase 'S' and plural for 'Secrets', dash character '-' between the words as separator)."
+          elif [ "$(gh repo list --json name,visibility | jq --raw-output '.[] | select(.name=="Match-Secrets") | .visibility')" != "PRIVATE" ]; then
+            failed=true
+            echo "::error::Match-Secrets repository visibility is set to PUBLIC. Set it to PRIVATE and try again."
           fi
           
           # Validate FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY
@@ -84,4 +116,4 @@ jobs:
           FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
           FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
-          GH_TOKEN: ${{ secrets.GH_PAT }}
+          GH_TOKEN: ${{ secrets.GH_PAT }} # necessary to set this, so that gh CLI commands in validate step use the Looper's GH_PAT
